### ISSUE TITLE
Phpstorm complains about multiple class definitions  because of ide-helper

### ISSUE THREAD

**Issue by mr-feek** [psalm/psalm-plugin-laravel#43]
Since we are generating ide-helper files, phpstorm complains about multiple class definitions.

Perhaps we should consider moving ide-helper to a suggested peer dependency, as I assume a lot of laravel developers will already have it installed and the files generated. Then the developer can configure the path to their phpstorm stubs file if they would like.

![image](https://user-images.githubusercontent.com/5747667/79270864-ba3a7500-7e53-11ea-83fe-82c4fdaf0c9e.png)

**Comment by muglug** [comment]
Should be fixed now

**Comment by brendt** [comment]
@muglug how was this fixed? PhpStorm still shows both options

![Screen Shot 2020-04-29 at 11 43 55](https://user-images.githubusercontent.com/6905297/80582294-bb040700-8a0e-11ea-9ff3-9a070b61d3f3.png)

**Comment by brendt** [comment]
Ah, I believe this wasn't tagged yet.

**Comment by muglug** [comment]
@mr-feek want to cut a release?

**Comment by mr-feek** [comment]
Released https://github.com/psalm/psalm-plugin-laravel/releases/tag/1.2.0

**Comment by brendt** [comment]
Awesome, thanks!
