### ISSUE TITLE
models.stubphp out of sync

### ISSUE THREAD

**Issue by brendt** [psalm/psalm-plugin-laravel#62]
Psalm reported following error: 

```
ERROR: InvalidArgument - app/Context/Product/Actions/UpdateEventGeneralCardAction.php:16:41 - Argument 2 of App\Context\Product\Actions\UpdateEventGeneralCardAction::saveProductDetail expects App\Context\Product\Models\ProductDetail, Illuminate\Database\Eloquent\Relations\BelongsTo provided (see https://psalm.dev/004)
        $this->saveProductDetail($data, $event->productDetail);
```

It seems like it didn't recognise `productDetail` as the relation.

So I did some digging in `_ide_helper_models.php`, where the property seemed to exist:

```php
* @property-read \App\Context\Product\Models\ProductDetail $productDetail
```

Looking at `models.stubphp` in `vendor/psalm/plugin-laravel/src/cache/models.stubphp` though, the property wasn't present. It seemed like this file was an outdated version.

I've tried reinstalling `psalm/plugin-laravel`, but the same stub file, missing the property gets generated.

Any ideas?

**Comment by brendt** [comment]
Doing some more digging into this, it seems like all `@property-read` properties are missing in `models.stubphp`

**Comment by brendt** [comment]
I'm using `dev-master` btw

**Comment by mr-feek** [comment]
Thanks for the report @brendt , I'll see if i can get this addressed this weekend. It probably has to do with our override of the ide helper models command: https://github.com/psalm/psalm-plugin-laravel/blob/master/src/FakeModelsCommand.php#L128

**Comment by mr-feek** [comment]
@brendt in the meantime, i think you should be able to load your own `_ide_helper_models.php` file as a stub file in your `psalm.xml` file.

**Comment by brendt** [comment]
Thanks for looking into this @mr-feek ! 

FYI for anyone reading this before the bug is fixed, I tried adding `_ide_helper_models.php` but psalm still reports the errors.

**Comment by mr-feek** [comment]
@brendt curious, does the problem still happen if the properties are declared in the doc blocks of the model itself? IE @param tag

**Comment by brendt** [comment]
@mr-feek it does, both with `@param` or `@property-read`

**Comment by brendt** [comment]
@mr-feek any update on this? Anything I can do to help?

**Comment by mr-feek** [comment]
Hey @brendt , I have a draft PR open for relation support — hoping to get around to finishing it up this weekend. 

Care to try it out and see if it fixes your issue? If it doesn’t, PRing a failing test case would be super helpful!

**Comment by mr-feek** [comment]
This is the draft PR i was referring to: https://github.com/psalm/psalm-plugin-laravel/pull/73

**Comment by mr-feek** [comment]
@brendt I believe this is now fixed on `dev-master`. I ran it on a project of mine with 40+ models and relations were working for me. Let me know!

**Comment by brendt** [comment]
Hi @mr-feek 

Thanks! 

I've noticed one type of error popping up now, which prevented me from further testing, and this one was new since updating to dev-master:

```
ERROR: TooManyTemplateParams - app/Context/Product/Models/Concerns/HasProductAttributes.php:12:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Models\ProductAttribute> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphToMany(
            ProductAttribute::class,
            'assigned_attribute',
            'product_assigned_attributes',
            'assigned_attribute_uuid'
        );
```

There were a few more instances, I suppose related:

```
ERROR: TooManyTemplateParams - app/Context/Product/Models/FieldOfStudy.php:26:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Types\Event\Models\Event> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphedByMany(Event::class, 'product');


ERROR: TooManyTemplateParams - app/Context/Product/Models/ProductAttribute.php:23:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Types\Event\Models\Event> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphedByMany(
            Event::class,
            'assigned_attribute',
            'product_assigned_attributes'
        );


ERROR: TooManyTemplateParams - app/Context/Product/Types/Event/Models/Event.php:107:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Models\FieldOfStudy> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphToMany(
            FieldOfStudy::class,
            'product',
            'product_field_of_study',
            'product_uuid'
        )->withPivot('credit_hours');
```

**Comment by mr-feek** [comment]
Ah yes, I have a todo for the morph relations! I never use them, so they confuse me a bit. I’ll dig in before cutting a new release

**Comment by brendt** [comment]
Maybe this could help: https://stitcher.io/blog/laravel-has-many-through

**Comment by brendt** [comment]
Oh no, those are morphs, not hasManyThrough; my bad

**Comment by brendt** [comment]
Just tried these changes out, they work as expected, thanks!

**Comment by mr-feek** [comment]
wahoo -- ill be tagging a new release once psalm tags theirs (because im dependent on a bug fix).

In the meantime, please create issues for any more bugs you run into!
